version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: watchdog
    versions:
    - 1.0.2
    - 2.0.0
    - 2.0.1
    - 2.0.2
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: sphinx
    versions:
    - 3.5.2
    - 3.5.3
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pip
    versions:
    - "21.0"
